# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Néfi Trindade Sant\Desktop\Login\tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 536)
        MainWindow.setStyleSheet("background-color: rgb(0, 129, 167);\n"
"color:rgb(255, 255, 255);\n"
"font: 15pt \"Bahnschrift Light SemiCondensed\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(90, 75, 301, 41))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border-style:outset;\n"
"font: 15pt \"Bahnschrift Light SemiCondensed\";\n"
"color:rgb(0, 0, 0)")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 150, 301, 41))
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border-style:outset;\n"
"font: 15pt \"Bahnschrift Light SemiCondensed\";\n"
"color:rgb(0, 0, 0)")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 225, 301, 41))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border-style:outset;\n"
"font: 15pt \"Bahnschrift Light SemiCondensed\";\n"
"color:rgb(0, 0, 0)")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(90, 300, 301, 41))
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"border-style:outset;\n"
"font: 15pt \"Bahnschrift Light SemiCondensed\";\n"
"color:rgb(0, 0, 0)")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(165, 390, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold SemiConden")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-radius:15px;\n"
"border-color:black;\n"
"font: 63 12pt \"Bahnschrift SemiBold SemiConden\";\n"
"color:rgb(0, 129, 167)\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(15, 30, 481, 30))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 30))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Digite seu nome"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Digite seu login"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "Digite a senha"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Repita a senha"))
        self.pushButton.setText(_translate("MainWindow", "Cadastrar"))
        self.label.setText(_translate("MainWindow", "Preencha os campos abaixo para cadastrar um novo usuário"))
